version: "3.5"
services:
  server:
    build: ./Server
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - struct-net 
  semihonest:
    build: ./SemiHonest
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - struct-net
  malicious:
    build: ./Malicious
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - struct-net 
networks:
  struct-net:
